version: "3.8"
services:  
  opal_client:
    # by default we run opal-client from latest official image
    image: authorizon/opal-client:latest
    environment:
      - OPAL_SERVER_URL=http://host.docker.internal:7002
    ports:
      # exposes opal client on the host machine, you can access the client at: http://localhost:7000
      - "7000:7000"
      # exposes the OPA agent (being run by OPAL) on the host machine
      # you can access the OPA api that you know and love at: http://localhost:8181
      # OPA api docs are at: https://www.openpolicyagent.org/docs/latest/rest-api/
      - "8181:8181"
    # this command is not necessary when deploying OPAL for real, it is simply a trick for dev environments
    # to make sure that opal-server is already up before starting the client.
    command: sh -c "/usr/wait-for.sh http://host.docker.internal:7002/ --timeout=20 -- /start.sh" 